
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openProject(path: string) : Promise<Result<Node<FileMetadata>[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProject(path: string) : Promise<Result<Node<FileMetadata>[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDocument(parent: Node<FileMetadata>, name: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_document", { parent, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameDocument(path: string, newName: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_document", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openDocument(path: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_document", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDocument(document: Document, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_document", { document, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addBlock(document: Document, path: string, kind: BlockKind, index: number | null) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_block", { document, path, kind, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBlock(document: Document, path: string, blockId: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_block", { document, path, blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderBlocks(document: Document, path: string, startIndex: number, endIndex: number) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_blocks", { document, path, startIndex, endIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateBlockContent(document: Document, path: string, blockId: string, content: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_block_content", { document, path, blockId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeBlockKind(document: Document, path: string, blockId: string, kind: BlockKind) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_block_kind", { document, path, blockId, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDocument(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_document", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanProjectDocuments() : Promise<Result<Node<FileMetadata>[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_project_documents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveDocument(sourcePath: string, targetPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_document", { sourcePath, targetPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateDocument(path: string) : Promise<Result<Document, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_document", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
documentChanged: DocumentChanged,
projectChanged: ProjectChanged
}>({
documentChanged: "document-changed",
projectChanged: "project-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type Block = { id: string; kind: BlockKind; content: string; vcs_state: VCSState }
export type BlockKind = "content" | "memo"
export type Document = { id: string; name: string; blocks: Block[] }
export type DocumentChangeKind = "Deleted" | "Renamed" | { Moved: { old_path: string; new_path: string } }
export type DocumentChanged = { document: Document; kind: DocumentChangeKind }
export type FileMetadata = { path: string; name: string }
export type Node<T> = { children: Node<T>[]; data: T }
export type ProjectChanged = null
export type VCSState = "default" | "added" | "modified" | "removed"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
